apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondupdate
  namespace: eksapp
  labels:
    app: secondupdate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secondupdate
  template:
    metadata:
      labels:
        app: secondupdate
    spec:
      containers:
        - name: secondupdate
          image: 265083127752.dkr.ecr.ap-south-1.amazonaws.com/ecr-secondupdate-crew-repo
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
