kind: Service
apiVersion: v1
metadata:
  name: secondupdate
  namespace: eksapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: secondupdate
